### ISSUE TITLE
Is it possible to get the name of the generated color ?

### ISSUE THREAD

**Issue by minedun6** [davidmerfield/randomColor#102]
Would it be possible to get the name of the color generated ?
Naming would follow wikipedia color naming 
[Wikipedia color names](https://en.wikipedia.org/wiki/List_of_colors:_A%E2%80%93F)

**Comment by davidmerfield** [comment]
Hello, this is not possible with randomColor right now. 

However, it would be a fun project to take a random color and find the nearest named color... but I'm going to consider this outside the scope of this particular script. Let me know if you have any questions!

**Comment by agurtovoy** [comment]
@minedun6 Checkout https://github.com/zeke/color-namer

**Comment by davidmerfield** [comment]
I'll consider this closed for now, thank you Aleksey!

**Comment by TrinasaurusRex** [comment]
@davidmerfield,

Would it be possible for randomColor to use the luminosity and hue names? e.g. Light blue, dark red, bright green. I feel like there should be a way to do this and I'm sure it's an easy reverse engineer, but I just can't figure it out.

#104

**Comment by davidmerfield** [comment]
Hi there! You should be able to modify [Color Namer](https://github.com/zeke/color-namer) to do this. Just define your own colors in a file like [basic.js](https://github.com/zeke/color-namer/blob/master/lib/colors/basic.js). I consider this beyond the scope of randomColor though and will keep this closed for now
