### ISSUE TITLE
Grabbing color name from random value

### ISSUE THREAD

**Issue by TrinasaurusRex** [davidmerfield/randomColor#104]
Is there any way to display the color name with the random color? If I were to generate a random color and it would fill the color depending on the hue and the shade depending on the luminosity?

e.g. Light blue, dark red, bright green

**Comment by ItsNickBarry** [comment]
See #102.

**Comment by TrinasaurusRex** [comment]
Hmm. I'm not looking to use the exact color names, just the light or dark and basic hue ranges already established in the color dictionary. 

`randomColor({
   luminosity: 'light',
   hue: 'blue'
});`
but reversed.

**Comment by davidmerfield** [comment]
Have followed up in #102, closing this for now.
