### ISSUE TITLE
Suggestion: If asked to return x colours, return x colours with sufficient contrast between them

### ISSUE THREAD

**Issue by logolab** [davidmerfield/randomColor#109]
I ran into the problem that I needed 5 colours but 2 of the returned colours were so close to each other that they were indistinguishable. It would be great if in that case the 5 colours would be random but sufficiently distinct from each other.

**Comment by logolab** [comment]
Just saw this on the todo list.... Sorry.

**Comment by davidmerfield** [comment]
No worries, there's pull request #106 by @m-bourkha which addresses this and I will review it imminently.

**Comment by logolab** [comment]
Could you let me know if the pull request has been merged?
It'd be great if the "sufficient difference between colours" problem could be eliminated. Super useful library otherwise.
