### ISSUE TITLE
Specific hue hex colors not working

### ISSUE THREAD

**Issue by HannesDeMets** [davidmerfield/randomColor#123]
When i pass the hexadecimal `#fec300` value to the hue key, i get the following error:

`var randomColor = randomColor({ hue: '#fec300' });`

<img width="450" alt="Screenshot 2019-04-29 at 14 56 20" src="https://user-images.githubusercontent.com/35343856/56897488-f764f600-6a8e-11e9-93e5-eb9ef5e92017.png">

I had the same result when testing with: `#fec200`, `#fec400`, `#fec500` and `#fec600`

**Comment by davidmerfield** [comment]
[Cannot reproduce](https://jsfiddle.net/d6af3qwn/) with the latest version of the library. Please send me a link to a page which demonstrates the issue

**Comment by maximtmartin** [comment]
This problem happens when you set count option to 1;

`randomColor({hue: '#fec300', count: 1})`

**Comment by KyleFoleyImajion** [comment]
Having the exact same issue with the color #FF00DB

**Comment by davidmerfield** [comment]
Understood, will fix

**Comment by SethPaulM** [comment]
Is there any update on the status of this fix?

**Comment by davidmerfield** [comment]
@SethPaulM No, but if you subscribe to this issue you will be notified when it's closed

**Comment by msd7manoj** [comment]
Is this bug fixed? Facing the same issue

**Comment by davidmerfield** [comment]
Should now be fixed in 0.6.1, available from npm right now!
