### ISSUE TITLE
How to deterministically return same colors on every call?

### ISSUE THREAD

**Issue by korroktheslavemaster** [davidmerfield/randomColor#125]
I'm generating colors inside a redux reducer, so I expect every call of `randomColor({seed: 1})` to return the same colors. Right now, since seed is internally incremented on each call, I get different colors. i.e. `randomColor({seed: 1}) !== randomColor({seed: 1})`
Is there a way to reset the seed so it becomes deterministic?

**Comment by korroktheslavemaster** [comment]
Just to clarify: I'm using this to generate `n` different colors for a chart using `randomColor({seed: n})` where `n` is a redux state variable that can change through the interface.
Right now my solution is to use https://github.com/reduxjs/reselect so that this function is not called multiple times for the same `n`

**Comment by davidmerfield** [comment]
This should now be fixed with the latest release on npm, please re-open if that's not the case!
