### ISSUE TITLE
gh sponsorships

### ISSUE THREAD

**Issue by pketh** [davidmerfield/randomColor#129]
I love this lib, I used it extensively when building Glitch, and use it a bunch for [kinopio.club](https://kinopio.club). 

I'm not sure how it works but, if you haven't already, could you signup for https://github.com/sponsors (or something else) so I can give at least a little cashmoneybling?

thxthx

**Comment by davidmerfield** [comment]
Kinopio is neat! But I must decline your offer. I'm glad to hear you have made of the script
