### ISSUE TITLE
Homepage/demo is down

### ISSUE THREAD

**Issue by g1eb** [davidmerfield/randomColor#130]
https://randomcolor.lllllllllllllllll.com/ seems to be down, see screenshot attached

<img width="639" alt="Screen Shot 2020-01-09 at 12 14 17 PM" src="https://user-images.githubusercontent.com/1916056/72101480-a4a83300-32d9-11ea-9777-eb20837e6dc7.png">

**Comment by davidmerfield** [comment]
Should have been fixed a while ago – sorry about this. Thank you for the report!
