### ISSUE TITLE
Convert project to typescript and implement test

### ISSUE THREAD

**Issue by aktselite** [davidmerfield/randomColor#152]
Hello!

I'm thrilled to contribute to this project and enhance my Git skills while helping out. After reviewing the project, I had an idea to add TypeScript support. TypeScript brings type safety, which can catch bugs early in development and make the code more reliable. Additionally, I plan to add tests to cover various edge cases and ensure the project's robustness.

I would be more than happy to work on these features if they align with your project's goals. Please let me know your thoughts, and I'm here to assist you in any way I can. 😊

**Comment by blobitty** [comment]
would love this

**Comment by aktselite** [comment]
Sorry, for late response, I was bussy with my exams.

So, I am very excited to work on this, I ma starting the work from today and will open PR as soon as possible.
But, this is my first time collaborating on a project, so may need some guidance throughout the process, So, I expect support from your side.

Thank you :)

**Comment by aktselite** [comment]
There's one thing i would like to ask.

While looking and testing the conversion functions like, HSVtoHSL or HexToHSB etc.. are returning array of floats instead of integers, For example:
`console.log(HSVtoHSL([ 44, 99, 99 ])); // Should return [ 44, 98, 50 ] but returns [ 44, 98.02, 49.995 ]`,

So i was wondering if this is intended feature, or I should fix it to return **array of integers** instead of **array of floats**

**Comment by aktselite** [comment]
I don't know if this behaviour is intended or not but i found that:
If you do: `console.log(randomColor(hue: 'monochrome', count: 3))` you get range error my guess is beacuse hueRange for monochrome is set to null when populating the dictionary by the function `loadColorBounds`, correct me if I am wrong... 

This can be easily fixed by setting hueRange for monochrome, I just don't know what range is for monochrome colors, according to me hue is same for monochrome colors... Again correct me if I am wrong

also if this is intended feature, we should implement check that, if hue is provided as monochrome, then we should not accept the count variable, I can add this check, just let me know which one isintended feature i will update according to that

**Comment by aktselite** [comment]
I noticed that, the file published on npm is different then the file avaliabl in this repo, and due to this I was scratching me head for eternity, I was wndering why its not working in the cloned repo but works in test project where I installed the npm package ;_;

Please update github repo ASAP...

**Comment by aktselite** [comment]
@blobitty Just asking... are you the owner of this repo or moderator or friend of the owner, like i found that, there are already type for this package and owner has not reviewed any issues/ PRs these days... So, is my effort worth, I will still continue the conversion even if its not worth it because I will learn a lot and I will still open the PR incase owner decides to accept it in future or whatever...
