### ISSUE TITLE
No HSV in CSS

### ISSUE THREAD

**Issue by mistic100** [davidmerfield/randomColor#25]
I guess the 'hsv' format was intended to be used in CSS, problem is that CSS does not support HSV, only HSL.

Check https://gist.github.com/xpansive/1337890 for a one liner converter (it works with hue between 0 and 360 and all others values between 0 and 1)

ps: I'm working on a PHP port, will tell you when ready :-)

**Comment by davidmerfield** [comment]
[Merged!](https://github.com/davidmerfield/randomColor/commit/0797dd103bca6b07f59069a0acb201cc664e0688)
