### ISSUE TITLE
Should be able to pass multiple color names

### ISSUE THREAD

**Issue by hth** [davidmerfield/randomColor#31]
What if I do not want random colors and one color cannot spread between 20 counts. Is it possible to support set of colors?

randomColor({hue: ['blue','monochrome'], luminosity: 'bright', count: 20});
randomColor({hue: ['blue','monochrome'], luminosity: 'light', count: 20});

**Comment by davidmerfield** [comment]
I'd honestly just concatenate two arrays of different colors – I'm not sure this would add enough to the library. Am closing this for now
