### ISSUE TITLE
Retrieve the same color...

### ISSUE THREAD

**Issue by biapar** [davidmerfield/randomColor#32]
Is't possible to generate a fix color ( not random )?

**Comment by davidmerfield** [comment]
Would you like to seed the generator? For example something like ```randomColor({seed: 'ABC'})``` would always return the same hex code?

**Comment by biapar** [comment]
Hi,

that is every time that I execute the page, I wish the same palette.

**Comment by davidmerfield** [comment]
This is now possible thanks to @koide with the lastest release.

randomColor({count: 10, seed: 1234}) will return the same palette each time.
