### ISSUE TITLE
Is there any way to always get the same colors?

### ISSUE THREAD

**Issue by SrVictorMaia** [davidmerfield/randomColor#40]
I know it is called random color, but it would be interesting if we had a way to just get a continuous stream of random colors in a way that doesn't change between different runs. Yes, I can just create a big array, but that is not the idea.

**Comment by davidmerfield** [comment]
Yes it is possible. Setting the 'seed' option will return the same result each time:

```javascript
randomColor({seed: 7843947})
```

You can combine this with other options too:

```javascript
randomColor({seed: 123, count: 20, hue: 'blue'});
```
