### ISSUE TITLE
Empty Options must be passed 

### ISSUE THREAD

**Issue by livemixlove** [davidmerfield/randomColor#43]
I get the following error when I call randomColor()  :

[...]/node_modules/randomcolor/randomColor.js:36
    if (options.seed && !seed) seed = options.seed;
               ^
TypeError: Cannot read property 'seed' of undefined

The simple fix:  randomColor({})

**Comment by davidmerfield** [comment]
I believe this issue was fixed with [this commit](https://github.com/davidmerfield/randomColor/commit/fdb4dc974cc38c46486c8e906ae9c7092550ab09).

Where did you get the copy of randomColor.js which still has this bug present? The latest version on GitHub should work

**Comment by livemixlove** [comment]
npm install randomcolor

Installed today.

**Comment by livemixlove** [comment]
(thanks for your work, btw!)

**Comment by davidmerfield** [comment]
npm now has [the latest, working version](https://www.npmjs.com/package/randomcolor). I dread to think how many people have downloaded the broken one :(

**Comment by davidmerfield** [comment]
Thanks for letting me know!
