### ISSUE TITLE
Exporting functions like HSVtoHSL, HSVtoRGB, HSVtoHex?

### ISSUE THREAD

**Issue by fritx** [davidmerfield/randomColor#46]
I find them quite useful but for now I just copy them directly into my source code
https://github.com/fritx/markppt/commit/ae7df02b5577cb6ce41dde6da60345365243b40b#diff-5f48f4b7cd5fa5aa6e97a127e55158deR271

**Comment by davidmerfield** [comment]
Hi Fritz! I'd rather not do this. Although the actual downsides of exporting these functions are insignificant, I'd prefer to keep the tool focussed as possible. There are some terrific libraries for color format conversion and I'd rather direct people to those instead.

**Comment by fritx** [comment]
Cool! Btw, what else libraries do you think are good to use?

**Comment by davidmerfield** [comment]
[Chroma](https://github.com/gka/chroma.js) and [Chromatist](https://github.com/jrus/chromatist) are both great.

**Comment by fritx** [comment]
Nice!
