### ISSUE TITLE
Different Color

### ISSUE THREAD

**Issue by Muneem** [davidmerfield/randomColor#49]
I think there should be feature which will make sure that it will always generate random unique color.

**Comment by Muneem** [comment]
and sir i think there should also be a feature of controlling shades

**Comment by davidmerfield** [comment]
Hi Muneem – both of these features are available and specified in the readme:

```javascript
// Returns a hex code for a light blue
randomColor({
   luminosity: 'light',
   hue: 'blue'
});

// Returns a hex code for a 'truly random' color
randomColor({
   luminosity: 'random',
   hue: 'random'
});
```
