### ISSUE TITLE
Format rgba not working

### ISSUE THREAD

**Issue by Marlysson** [davidmerfield/randomColor#51]
I'm using the library for to make a color with format rgba:

    color = randomColor({
        hue:'random',
        format:'rgba'
    });

    console.log('rgba',color);

console:
> rgba #4ddd90

I'm wrong or the suport for this feature yet not complete? I saw the issues about this feature.

Thank you for attention.

**Comment by davidmerfield** [comment]
This feature is not included in older versions. Update to 0.4.1 and it should work as expected:

``` javascript
randomColor({format: 'rgba', hue: 'random'})
// "rgba(32, 170, 78, 0.2418320132419467)"
```
 Closing this for now, let me know if I should re-open.
