### ISSUE TITLE
Dedicate this to Public Domain

### ISSUE THREAD

**Issue by davidmerfield** [davidmerfield/randomColor#52]
I would like to dedicate this project to the public domain and change the license on this repo from MIT to the more permissive [CC0](https://creativecommons.org/publicdomain/zero/1.0/). **If you are one of the 14 contributors, do you consent to this change in license?** If so, please leave a comment on this issue saying 'yes' or 'lgtm' or however you typically express consent. If not, just comment 'no' and I'll close this issue.

Sorry for the bother.

- [x] @davidmerfield
- [x] @kkirsche 
- [x] @mistic100 
- [x]  @DanielRosenwasser 
- [x] @koide 
- [x] @riley 
- [x] @daviesgeek 
- [x] @bilalq 
- [x] @onevcat 
- [x] @cgmartin 
- [x] @lijunle 
- [x] @afc163 
- [x] @kevinwuhoo 
- [x] @Zepx 
- [x] @yageek

**Comment by kkirsche** [comment]
Yes

-----
Please excuse the brevity, this was sent from a mobile device.

**Comment by DanielRosenwasser** [comment]
Yes.

Tip: you can make an actual checklist in GitHub by prefixing each of the boxes with a hyhen:

- [ ] Look
- [ ] at
- [ ] these
- [ ] checkboxes

**Comment by mistic100** [comment]
yes
----
I'm not familiar with licences, does this have an effect on projects that share the "intellectual algorithm" or whatever (like https://github.com/mistic100/RandomColor.php) ?

**Comment by mistic100** [comment]
BTW I read some arguments against using Unlicense
http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense
https://github.com/docopt/docopt.rs/issues/1
FYI

**Comment by riley** [comment]
:+1:  I'm also not super familiar with licenses, but it looks fine.

**Comment by DanielRosenwasser** [comment]
> BTW I read some arguments against using Unlicense

For what it's worth, I agree for the same reasons; a new license will hurt more than it helps for people in other countries. If you want more permissive than MIT, I'd suggest Apache 2. Ultimately I'd like to respect that it's your project though, so it's your call.

**Comment by koide** [comment]
I don't really like the Unlicense much (I think it might end up being
trouble in the long run), but my contribution is certainly not significant
enough to give me the moral right to block the original author's desire.

I would certainly have made the change anyway if the code had been
unlicensed by then.

As long as it doesn't go proprietary, I'm okay.

Summing up, this is a long and contrived yes.

V.

**Comment by davidmerfield** [comment]
It seems [CC0](https://creativecommons.org/publicdomain/zero/1.0/) is the better solution. I was unaware that the unlicense was illegal in Germany. 

Sorry for taking this time out of all of your work days for this rather trivial issue – I'm trying to move all of my personal projects to the public domain. The joys of open-source!

@koide Never, ever, ever, would this go proprietary
@DanielRosenwasser Thanks for the tip!

**Comment by daviesgeek** [comment]
Yes

**Comment by bilalq** [comment]
Yes

**Comment by onevcat** [comment]
No problem for me.

**Comment by lijunle** [comment]
Yes

Mine is trivial changes, please go ahead with it.

Thanks!

**Comment by afc163** [comment]
Yes :santa:

**Comment by cgmartin** [comment]
Yes :+1:

**Comment by kevinwuhoo** [comment]
Sounds great! :shipit:

**Comment by Zepx** [comment]
I think you have the biggest say, but I'm ok for it!

**Comment by yageek** [comment]
Fine for me

**Comment by davidmerfield** [comment]
Thanks everyone!
