### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by daviesgeek** [davidmerfield/randomColor#53]
I'd originally included some tests in [my pull request](https://github.com/davidmerfield/randomColor/pull/48), but removed them due to [@davidmerfield's comment](https://github.com/davidmerfield/randomColor/pull/48#issuecomment-152874589)

I'd love to add some tests, but wanted to open up the discussion on what frameworks to use (etc., etc.), as @davidmerfield said, "I don't want to use Karma/Jasmine"

**Comment by davidmerfield** [comment]
Since this has been open for over a year, I'm going to close this for now. Best, David
