### ISSUE TITLE
Seeds only apply the first time. 

### ISSUE THREAD

**Issue by timdorr** [davidmerfield/randomColor#54]
I expect the following to be true
```js
randomColor({seed: 1}) === randomColor({seed: 1})
```
However, it is not. This is a problem where I want to have a randomly generated color based on the hash of a string. Think something like [Github's Identicons](https://github.com/blog/1586-identicons) for new users without an avatar. 

[Here is the line causing the issue](https://github.com/davidmerfield/randomColor/blob/master/randomColor.js#L41). The seed value is hidden inside that closure and persists across calls. If you remove the `&& !seed`, that should be all that's needed to keep `randomColor` deterministically random.

**Comment by davidmerfield** [comment]
I've fixed this in commit [9759c8d](https://github.com/davidmerfield/randomColor/commit/9759c8d4a4469eb08d76925ce9e475fb89fba098)

Thank you!

**Comment by timdorr** [comment]
No, thank you!
