### ISSUE TITLE
Define color dictionary

### ISSUE THREAD

**Issue by neverfox** [davidmerfield/randomColor#55]
It would be nice to have the option to define the color dictionary, e.g one could pass in a palette of color such as the Material Design palette, and those would be the only colors returned from the randomizer.

**Comment by nathanpjones** [comment]
I'm not sure what you're asking for here. Sounds like you just want to select a random element from an array. There are certainly easier ways to do that.

**Comment by davidmerfield** [comment]
@neverfox Has @nathanpjones answered your question? I'm closing this for now.
