### ISSUE TITLE
Last update has changed the colors

### ISSUE THREAD

**Issue by AoDev** [davidmerfield/randomColor#56]
Hello. First thank you for the module.

I wanted to ask you about this commit. 
https://github.com/davidmerfield/randomColor/commit/9759c8d4a4469eb08d76925ce9e475fb89fba098

We have been using your module for a while now and the colors were just fine. But after updating to this last version,  our colors changed and it could be considered a "breaking change". Is there a way to get back to the same behaviour / colors than before?

I don't know if it's only for us but this change might have "broken" expected colors in every project using it. (we have been playing with the seed until we found the colors we liked)

**Comment by davidmerfield** [comment]
Very sorry about this. I suppose you could install the former version on npm? Or fetch that version from github directly. I believe the fix was worth the breaking change. Closing this for now. Best, David

**Comment by AoDev** [comment]
I have adapted to the changes. But I suggest that, although it's "random color", you should take it into account if an update changes the color again ;)

thanks
