### ISSUE TITLE
How to get pair of related (light/dark) colours

### ISSUE THREAD

**Issue by micheledallatorre** [davidmerfield/randomColor#73]
Hello,
I'm using www.chartjs.org to display some charts.
I would need to get some "related" colors, e.g. a light blue and a dark blue, to be used for hover and background colors, for example in a bar chart: http://www.chartjs.org/docs/#bar-chart

To do that, I use the alpha channel:
```javascript
// define a green colour with alpha = 1
var green = 'rgba(172,216,86, 1)';
// define the same color but with alpha = 0.5
var greenHighlight = 'rgba(172,216,86, 0.5)';
```

Is there a way, using your library, to get an array of two colors, with the same rgb values but with different alpha (e.g. alpha = 1 and alpha = 0.5)?

Thanks!

**Comment by davidmerfield** [comment]
The library can't do this directly but I'd do something like this then manipulate the result to get your desired arrays:

```javascript
var greens = randomColor({
   hue: 'green',
   format: 'rgbArray',
   count: 10
});
```
