### ISSUE TITLE
Напишите нормальную инструкцию "как использовать случайный цвет"

### ISSUE THREAD

**Issue by alfakrai** [davidmerfield/randomColor#74]
Здравствуйте. Напишите понятную нормальную инструкцию о том, как использовать ваш скрипт. Мне не понятно, как классу дать случайный цвет

**Comment by davidmerfield** [comment]
Hi alfakrai, I'm sorry but this is not the place for general questions about Javascript. MDN has some great [resources for learning javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript). Am closing this for now.
