### ISSUE TITLE
Should string seed be a number

### ISSUE THREAD

**Issue by kounelios13** [davidmerfield/randomColor#75]
The docs state that the seed value must be an integer or a string.What if the string you try to pass is not a number?

**Comment by tiwo** [comment]
The `parseInt(options.seed, 10))` in line 44 will convert most strings to "NaN", leading to an error further down the road.

**Comment by davidmerfield** [comment]
Hi @kounelios13, @tiwo is quite correct. I'm going to consider this closed for now.
