### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by zaynetro** [davidmerfield/randomColor#78]
Hi, there were some changes made to the library since v0.4.4 release notably alpha option support. I was wondering whether a new version could be published to npm.

#77 is also related

Thanks!

**Comment by Koshux** [comment]
I would also like to use the alpha option however as Zaynetro pointed out, the alpha is mentioned within the GitHub docs but not in the published version on npmjs.  Therefore usages of alpha are ignored.

**Comment by DZDomi** [comment]
Would be very nice if the recent version is available to npm!

**Comment by davidmerfield** [comment]
Whoops – apologies for the delay. Thanks for catching this.
