### ISSUE TITLE
Monochrome with Random Luminosity Isn't Monochrome

### ISSUE THREAD

**Issue by x9xjdzz9** [davidmerfield/randomColor#79]
When I call randomColors with monochrome hue and random luminosity, the resulting colors are not monochrome.

http://codepen.io/x9xjdzz9/pen/rjJyjJ

**Comment by jackwilsdon** [comment]
It looks like this is due to [this](https://github.com/davidmerfield/randomColor/blob/108d646/randomColor.js#L113) `if` statement. I don't see a reason why the two statements couldn't be swapped so that we check for `monochrome` first.

**Comment by davidmerfield** [comment]
@jackwilsdon you're quite right, thank you for catching that. Would be happy to merge a PR if you're interested in the credit, otherwise will do this later today.

**Comment by davidmerfield** [comment]
Thanks Jack!
