### ISSUE TITLE
Possible to exclude colours?

### ISSUE THREAD

**Issue by Koshux** [davidmerfield/randomColor#82]
First of all thank you for this library!  Secondly, I encountered a situation where I would like to generate colours sequentially however once a colour has been generated, I would like the next generated colours to exclude the already existing ones (given an array of some sort).  Would you think this be possible?

I just realised that issue #58 is practically the same query.

**Comment by card100** [comment]
Double https://github.com/davidmerfield/randomColor/issues/58

**Comment by davidmerfield** [comment]
Going to close this since it is a duplicate of #58, thanks @Koshux and @card100.
