### ISSUE TITLE
Do hue's overlap?

### ISSUE THREAD

**Issue by wagenaartje** [davidmerfield/randomColor#88]
I'm wondering. If you create randomcolros with `hue: 'pink'` and `hue: 'purple'`, could there be overlapping colors? By eye I can't really tell, but it seems like there are some overlapping colors.

_So I ran this through a neural network, and it seems like they are overlapping (it can't classify them independently correctly)_

https://wagenaartje.github.io/neataptic/articles/classifycolors/

**Comment by davidmerfield** [comment]
They do not overlap. You can see the definitions of the hue boundaries here:

https://github.com/davidmerfield/randomColor/blob/master/randomColor.js#L321

For example, I've defined orange as HSV colors with an H value from [19 to 46](https://github.com/davidmerfield/randomColor/blob/master/randomColor.js#L337).
