### ISSUE TITLE
Possible to avoid colors similar to a given array of hex values?

### ISSUE THREAD

**Issue by adambedford** [davidmerfield/randomColor#94]
I'm working on an app that has a tagging feature and I'd like to assign a random, attractive color to each user-generated tag. User's create tags one at a time, so I only need one random color at a time, however I'd like each generated color to be substantively different from the previous colors that have been generated for a user, so the tag colors end up actually being different colors.

Is it possible to provide a list of colors to avoid during the random color generation process? The generator should also avoid colors that are similar to the previous values? 

I suppose that if the generator is truly random, this might not be as big of an issue as I'm imagining. Has anyone tackled anything like this before?

**Comment by davidmerfield** [comment]
Hi Adam, I'm going to merge this under #50. This is a good idea, will get around to working on it at some point...
