### ISSUE TITLE
is there a typings for this to be used in Angular 2?

### ISSUE THREAD

**Issue by tylerlindell** [davidmerfield/randomColor#95]
I have converted this into an angular service for my own purposes but it would be great if there was a typings file for your tool.

Here's a link to my service: https://gist.github.com/tylerlindell/130586743d41fede94c464f0b66a7126

it only generates one random color at a time but it does the job for what I need right now

**Comment by SmallhillCZ** [comment]
https://www.npmjs.com/package/@types/randomcolor ?

**Comment by suparnavg** [comment]
@tylerlindell thank you so much for that service script!

**Comment by tylerlindell** [comment]
@SmallhillCZ that looks promising, have you tested it?

**Comment by tylerlindell** [comment]
@suparnavg you got it sir!

**Comment by SmallhillCZ** [comment]
No in the end I just used the service.

**Comment by davidmerfield** [comment]
Closing for now. Please direct these inquiries to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues?utf8=%E2%9C%93&q=randomcolor). I don't consider this the responsibility of randomColor.
