### ISSUE TITLE
Seeded colors are indistinguishable to human eye after second generated color

### ISSUE THREAD

**Issue by darkmeton** [davidmerfield/randomColor#96]
The second and third seeded colours are very similar to the human eye. I am using a unique string as seed, of small length, 4-6 characters.

**Comment by davidmerfield** [comment]
Hi Michael, I don't quite understand. Can you give me an example of the code you're using, the result you'd expect, and the result you're currently getting?

**Comment by davidmerfield** [comment]
Closing this for now...
