### ISSUE TITLE
Greyscale options

### ISSUE THREAD

**Issue by james-ff** [davidmerfield/randomColor#97]
Hi, is it possible to set up options in order to get a greyscale that does not go too light? I have it set up on monochrome at the moment, but I'm using a white background and some of the text isn't readable when it goes to white or too close to white. I'm sure there is a simple solution, just struggling to find it by myself. Many Thanks!

Note:
- I am using randomColor via this library https://github.com/madox2/react-tagcloud

**Comment by davidmerfield** [comment]
Yes, but you'll need to modify the [maximum brightness value](https://github.com/davidmerfield/randomColor/blob/master/randomColor.js#L148). Try changing it to 80 or 90 and see what works for you.
